package aws

import (
	"fmt"
	"strings"
)

// GenerateEnvironmentYAML generates the environment.yml reference file
// directly (not via a Terraform local_file resource), mirroring
// generate_environment_yaml. Used as an alternative to the Terraform
// output when the caller wants the YAML without applying anything.
//
// Rendered by hand rather than through a YAML library: Python's own
// yaml.dump(default_flow_style=False, sort_keys=False) output for this
// specific shape (flat key/value pairs, two list-valued keys, no nested
// maps) is fully reproducible with plain string formatting, and every
// value here is either a plain string, bool, int, or flat string list --
// nothing that would need a real YAML encoder's escaping/quoting rules
// to render correctly.
func GenerateEnvironmentYAML(
	name, region, vpcID string,
	publicSubnets, privateSubnets []string,
	ecsClusterARN string,
	albARN, albListenerARN, albSecurityGroupID *string,
	retainDataOnDestroy bool,
	logRetentionDays int,
	tags map[string]string,
	tagOrder []string,
	awsEndpoint *string,
) string {
	var b strings.Builder

	fmt.Fprintf(&b, "%s: %s\n", pyYAMLKey("#"), pyYAMLScalar(fmt.Sprintf("Generated by: composey init env --provider aws --name %s", name)))
	fmt.Fprintf(&b, "%s: %s\n", pyYAMLKey("# Usage"), pyYAMLScalar(fmt.Sprintf("composey up --env %s/environment.yml", name)))
	fmt.Fprintf(&b, "target: aws\n")
	fmt.Fprintf(&b, "name: %s\n", pyYAMLScalar(name))
	fmt.Fprintf(&b, "region: %s\n", pyYAMLScalar(region))
	fmt.Fprintf(&b, "vpc_id: %s\n", pyYAMLScalar(vpcID))
	writeYAMLStringList(&b, "public_subnets", publicSubnets)
	writeYAMLStringList(&b, "private_subnets", privateSubnets)
	fmt.Fprintf(&b, "ecs_cluster_arn: %s\n", pyYAMLScalar(ecsClusterARN))
	fmt.Fprintf(&b, "retain_data_on_destroy: %s\n", pyYAMLBool(retainDataOnDestroy))
	fmt.Fprintf(&b, "log_retention_days: %d\n", logRetentionDays)

	if albARN != nil && *albARN != "" {
		fmt.Fprintf(&b, "alb_arn: %s\n", pyYAMLScalar(*albARN))
	}
	if albListenerARN != nil && *albListenerARN != "" {
		fmt.Fprintf(&b, "alb_listener_arn: %s\n", pyYAMLScalar(*albListenerARN))
	}
	if albSecurityGroupID != nil && *albSecurityGroupID != "" {
		fmt.Fprintf(&b, "alb_security_group_id: %s\n", pyYAMLScalar(*albSecurityGroupID))
	}
	if len(tags) > 0 {
		fmt.Fprintf(&b, "tags:\n")
		for _, k := range tagOrder {
			fmt.Fprintf(&b, "  %s: %s\n", pyYAMLKey(k), pyYAMLScalar(tags[k]))
		}
	}
	if awsEndpoint != nil && *awsEndpoint != "" {
		fmt.Fprintf(&b, "aws_endpoint: %s\n", pyYAMLScalar(*awsEndpoint))
	}

	return b.String()
}

func writeYAMLStringList(b *strings.Builder, key string, items []string) {
	if len(items) == 0 {
		fmt.Fprintf(b, "%s: []\n", key)
		return
	}
	fmt.Fprintf(b, "%s:\n", key)
	for _, item := range items {
		fmt.Fprintf(b, "- %s\n", pyYAMLScalar(item))
	}
}

func pyYAMLBool(v bool) string {
	if v {
		return "true"
	}
	return "false"
}

// yamlReservedScalars mirrors the bareword values PyYAML's default
// resolver would parse as something other than a plain string (bool,
// null), which forces a string carrying one of these exact spellings to
// be quoted so it round-trips as a string rather than silently becoming
// a boolean/null on the next load.
var yamlReservedScalars = map[string]bool{
	"true": true, "false": true, "yes": true, "no": true, "on": true, "off": true,
	"null": true, "~": true, "": true,
}

// pyYAMLScalar quotes a scalar string value exactly when PyYAML's own
// default emitter would, confirmed against live PyYAML output rather
// than assumed from the YAML spec (2026-08-06): a colon followed by a
// space, a value ending in a colon, or a value that would otherwise
// resolve to a non-string scalar (true/false/null/etc). Every value this
// this file actually emits (names, ARNs, subnet/VPC IDs, URLs) is checked
// against these rules rather than assumed safe -- an ARN's colons are
// never followed by a space, so they pass through unquoted, matching a
// live PyYAML run on the same value.
func pyYAMLScalar(s string) string {
	needsQuote := yamlReservedScalars[strings.ToLower(s)] ||
		strings.Contains(s, ": ") ||
		strings.HasSuffix(s, ":") ||
		strings.HasPrefix(s, "#") ||
		strings.HasPrefix(s, " ") ||
		strings.HasSuffix(s, " ")
	if !needsQuote {
		return s
	}
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

// pyYAMLKey quotes a mapping key using the same rule as pyYAMLScalar,
// since PyYAML applies its scalar-quoting logic to keys too (confirmed:
// "#" and "# Usage" both come out single-quoted).
func pyYAMLKey(s string) string {
	return pyYAMLScalar(s)
}
