#!/usr/bin/env bash
#
# End-to-end smoke test against real Azure.
#
# Creates environment with 'composey init --provider azure', compiles a
# compose file, deploys the resulting app, then polls the Container App
# FQDN until it serves a page. EVERYTHING is torn down on exit (success
# or failure) via a trap.
#
# Usage:
#   scripts/smoke-test-azure.sh
#   COMPOSE=examples/hello/compose.yml scripts/smoke-test-azure.sh
#   KEEP=1 scripts/smoke-test-azure.sh          # skip teardown to inspect resources
#   STATE_RG=... NAME=ci42 scripts/smoke-test-azure.sh --destroy-only
#
# Requires: terraform, go, curl, az (Azure CLI), python3 (for
# assert_managed.py only)
#
set -euo pipefail

# --- Config (override via environment) --------------------------------------
NAME="${NAME:-smoke}"                                 # environment name
COMPOSE="${COMPOSE:-examples/hello/compose.yml}"      # app to deploy
PROJECT="${PROJECT:-hello}"                            # composey project name
HTTP_PATH="${HTTP_PATH:-/}"                            # path to poll
EXPECT="${EXPECT:-Server name}"                        # string expected in HTTP body
POLL_TIMEOUT="${POLL_TIMEOUT:-300}"                    # seconds to wait for healthy app
KEEP="${KEEP:-0}"                                      # 1 = do not destroy afterwards
# Where the application is deployed. Distinct from STATE_LOCATION: one is the
# region under test, the other is where the state blob lives, and conflating
# them meant changing either moved both.
#
# Not eastus: this subscription is offer-restricted there for PostgreSQL
# Flexible Server, which fails with LocationIsOfferRestricted twenty minutes
# into an apply.
#
# Not uksouth or northeurope for anything touching Azure Managed Redis:
# both have failed Balanced_B0/B1 creation with InsufficientCapacity
# (confirmed against real Azure 2026-08-04). francecentral has neither
# restriction and was confirmed clean for both Postgres and Redis the same
# day — prefer it whenever the example includes a cache.
REGION="${REGION:-francecentral}"                     # region to deploy into
STATE_RG="${STATE_RG:-}"                               # Resource Group for remote state; empty = local
STATE_LOCATION="${STATE_LOCATION:-eastus}"             # location of STATE_RG storage
STATE_ACCOUNT="${STATE_ACCOUNT:-composeyacceptstate}"  # storage account holding state
STATE_CONTAINER="${STATE_CONTAINER:-tfstate}"          # blob container within it

# Resolve paths relative to the repo root (this script lives in scripts/).
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_DIR="$ROOT/build/$NAME-environment-azure"          # generated by 'composey init'
BUILD_DIR="$ROOT/build/$PROJECT-azure"
COMPOSEY="$ROOT/composey-go/composey-go"

TF="terraform"

log()  { printf '\n\033[1;34m==>\033[0m %s\n' "$*"; }
fail() { printf '\n\033[1;31mFAIL:\033[0m %s\n' "$*" >&2; exit 1; }

# --- Azure authentication ----------------------------------------------------
# Terraform's own credential discovery is left alone deliberately. In CI the
# ARM_CLIENT_ID/SECRET/TENANT_ID environment variables authenticate as the
# service principal; on a developer machine none are set and Terraform falls
# back to `az login`.
#
# Do not force ARM_USE_CLI=true here. The azurerm *backend* rejects a CLI
# session owned by a service principal outright ("Authenticating using the
# Azure CLI is only supported as a User"), even though the provider tolerates
# it — so forcing CLI auth breaks remote state in CI while appearing to work
# locally.

# --- Remote state ------------------------------------------------------------
# State on a CI runner is ephemeral. When STATE_RG is set we use an Azure Blob
# Storage backend so a leaked run stays destroyable from any machine.
#
# The storage account has shared-key access disabled, so the backend must
# authenticate with Entra ID (use_azuread_auth) rather than an account key.
# That works from the CI service principal and from a developer's az login
# alike, provided the identity holds Storage Blob Data Contributor on the
# account. See ci/README.md.
write_backend() {
  local dir="$1" key="$2"
  [[ -n "$STATE_RG" ]] || return 0
  # Falling back to local state here is what previously made a leaked run
  # unrecoverable, so a half-configured backend is an error, not a warning.
  [[ -n "$STATE_ACCOUNT" ]] || fail "STATE_RG is set but STATE_ACCOUNT is empty: refusing to fall back to local state"
  cat > "$dir/backend_ci.tf" <<TF
# Generated by scripts/smoke-test-azure.sh — not checked in.
terraform {
  backend "azurerm" {
    resource_group_name  = "$STATE_RG"
    storage_account_name = "$STATE_ACCOUNT"
    container_name       = "$STATE_CONTAINER"
    key                  = "$key"
    use_azuread_auth     = true
  }
}
TF
}

state_hint() {
  [[ -n "$STATE_RG" ]] || return 0
  echo "  State kept at $STATE_ACCOUNT/$STATE_CONTAINER/acceptance/$NAME/ — destroy later with:"
  echo "    STATE_RG=$STATE_RG NAME=$NAME PROJECT=$PROJECT scripts/smoke-test-azure.sh --destroy-only"
}

# Called only when both stacks destroyed cleanly. State that describes no
# resources is worse than useless: --destroy-only against it reports success
# having done nothing, which is the failure mode the backend exists to prevent.
# A failed teardown keeps its state, because that is the recovery path.
#
# The account has blob versioning and 30-day soft delete, so this is reversible
# if a destroy reported success while leaving something behind.
purge_state() {
  [[ -n "$STATE_RG" && -n "$STATE_ACCOUNT" ]] || return 0
  az storage blob delete-batch \
    --account-name "$STATE_ACCOUNT" \
    --source "$STATE_CONTAINER" \
    --pattern "acceptance/$NAME/*" \
    --auth-mode login >/dev/null 2>&1 \
    || echo "  NOTE: could not remove state under acceptance/$NAME/ — harmless, prune later."
}

# --- Teardown ----------------------------------------------------------------
CLEANED=0
cleanup() {
  local status=$?
  [[ "$CLEANED" == "1" ]] && exit $status
  CLEANED=1

  if [[ "$KEEP" == "1" ]]; then
    log "KEEP=1 set — leaving resources up. Destroy later with:"
    echo "  (cd $BUILD_DIR && $TF destroy -auto-approve)"
    echo "  (cd $ENV_DIR && $TF destroy -auto-approve)"
    exit $status
  fi

  log "Tearing down (exit status $status)…"
  local leaked=0
  
  if [[ -d "$BUILD_DIR" ]]; then
    (cd "$BUILD_DIR" && eval "$TF destroy -auto-approve") \
      || { leaked=1; echo "WARNING: app destroy failed — CHECK THE CONSOLE for orphaned resources."; }
  fi
  if [[ -d "$ENV_DIR" ]]; then
    (cd "$ENV_DIR" && eval "$TF destroy -auto-approve") \
      || { leaked=1; echo "WARNING: environment destroy failed — CHECK RESOURCE GROUP manually."; }
  fi

  if (( leaked == 1 )); then
    state_hint
  else
    purge_state
  fi
  exit $status
}
trap cleanup EXIT INT TERM

# --- Destroy-only mode -------------------------------------------------------
if [[ "${1:-}" == "--destroy-only" ]]; then
  [[ -n "$STATE_RG" ]] || fail "--destroy-only needs STATE_RG (runs with local state are not recoverable)"
  log "Destroy-only mode for environment '$NAME'."

  write_backend "$ENV_DIR" "acceptance/$NAME/environment.tfstate"
  (cd "$ENV_DIR" && eval "$TF init -input=false -reconfigure")

  if [[ -f "$BUILD_DIR/main.tf.json" ]]; then
    write_backend "$BUILD_DIR" "acceptance/$NAME/$PROJECT.tfstate"
    (cd "$BUILD_DIR" && eval "$TF init -input=false -reconfigure")
  else
    rm -rf "$BUILD_DIR"
    echo "  NOTE: no $BUILD_DIR/main.tf.json — skipping the app stack."
    echo "        To destroy it too, first run:"
    echo "          $COMPOSEY main -f \$COMPOSE -e $ENV_DIR/environment.yml -p $PROJECT -o $BUILD_DIR"
  fi

  exit 0
fi

# --- 0. Build the Go binary ---------------------------------------------------
# Built fresh rather than trusted from a stale copy on PATH: this script
# exists to catch real regressions, and a stale binary would defeat that
# the moment composey-go's source changed underneath it.
log "Building composey-go…"
(cd "$ROOT/composey-go" && go build -o composey-go ./cmd/composey)

# --- 1. Create environment with composey init ---------------------------------
log "Creating Azure environment '$NAME' with composey init…"
rm -rf "$ENV_DIR"
cd "$ROOT"
"$COMPOSEY" init --provider azure --name "$NAME" --region "$REGION" --output "$ENV_DIR"

write_backend "$ENV_DIR" "acceptance/$NAME/environment.tfstate"
cd "$ENV_DIR"

eval "$TF init -input=false -reconfigure"
eval "$TF apply -auto-approve"

# Get the Container Apps Environment info from the output
log "Environment created. Getting Container App info..."

# --- 2. Compile the app ------------------------------------------------------
log "Compiling $COMPOSE with composey for Azure…"
cd "$ROOT"
"$COMPOSEY" main -f "$COMPOSE" -e "$ENV_DIR/environment.yml" -p "$PROJECT" -o "$BUILD_DIR"

# --- 3. Deploy the app -------------------------------------------------------
log "Deploying app '$PROJECT' to Azure…"
write_backend "$BUILD_DIR" "acceptance/$NAME/$PROJECT.tfstate"
cd "$BUILD_DIR"

eval "$TF init -input=false -reconfigure"
# azurerm_cdn_frontdoor_origin is created with enabled=false regardless of
# what is configured — a known, unresolved provider bug (confirmed against
# real Azure 2026-08-05: hashicorp/terraform-provider-azurerm#31647). Any
# azurerm_cdn_frontdoor_route depending on that origin fails its first apply
# with "Please make sure that the originGroup is created successfully and at
# least one enabled origin is created under the origin group." A second
# apply always succeeds: Terraform detects the drift on refresh and flips the
# origin to enabled before the route is attempted again.
#
# A -target'd retry was tried first, to avoid touching anything else on the
# second apply — but -target pulls in the whole dependency chain behind the
# route (origin -> Container App -> Postgres connection string), so it still
# re-touched azurerm_postgresql_flexible_server and hit a second bug: Azure
# assigns that resource's `zone` itself, and any plan that reaches it tries
# to "correct" that real value, which the API rejects
# (models/azure.py's PostgreSQLFlexibleServer now carries
# `lifecycle.ignore_changes: ["zone"]` so that no longer happens on *any*
# plan, not just this retry). With that fixed at the source, retrying the
# whole apply is simple and no longer trades one bug for another.
if ! eval "$TF apply -auto-approve" 2>&1 | tee /tmp/tf-apply-app.log; then
  if grep -q "at least one enabled origin is created under the origin group" /tmp/tf-apply-app.log; then
    log "Front Door origin race hit (known azurerm provider bug #31647) — retrying apply…"
    eval "$TF apply -auto-approve"
  else
    fail "terraform apply failed for the app stack"
  fi
fi
# `terraform output -raw` prints its "No outputs found" warning on stdout, so a
# missing output is captured as the hostname rather than as an empty string.
# The previous state-show fallback could not have covered for that either: it
# addressed azurerm_container_app.main, but apps are keyed by service name.
# Insist on a value that looks like a hostname instead.
CONTAINER_APP_FQDN="$(eval "$TF output -raw fqdn" 2>/dev/null || true)"

[[ "$CONTAINER_APP_FQDN" =~ ^[A-Za-z0-9.-]+$ ]] \
  || fail "app stack published no usable fqdn output (got: ${CONTAINER_APP_FQDN:-<empty>})"
log "Container App FQDN: $CONTAINER_APP_FQDN"

url="https://$CONTAINER_APP_FQDN$HTTP_PATH"
log "Polling $url (up to ${POLL_TIMEOUT}s)…"
deadline=$(( SECONDS + POLL_TIMEOUT ))
served=0
body=""
while (( SECONDS < deadline )); do
  body="$(curl -sS --max-time 5 "$url" 2>/dev/null || true)"
  if [[ "$body" == *"$EXPECT"* ]]; then
    served=1
    break
  fi
  printf '.'
  sleep 5
done
if (( served != 1 )); then
  echo
  echo "----- last response (for diagnosis) -----"
  echo "${body:-<no response>}" | head -20
  fail "timed out after ${POLL_TIMEOUT}s waiting for '$EXPECT' at $url"
fi

log "App is live — response contains '$EXPECT'. 🎉"
echo "----- response -----"
echo "$body" | head -20

# --- 5. Managed-resource assertions ------------------------------------------
log "Asserting managed substitutions against applied Azure state…"
( cd "$BUILD_DIR" && eval "$TF show -json" ) | python3 "$ROOT/scripts/assert_managed.py" \
  || fail "managed substitution assertions failed"

log "SUCCESS — everything verified on real Azure."
exit 0
