#!/usr/bin/env bash
#
# End-to-end smoke test against real Azure.
#
# Creates environment with 'composey init env --provider azure', compiles a compose file,
# deploys the resulting app, then polls the Container App FQDN until it serves a page.
# EVERYTHING is torn down on exit (success or failure) via a trap.
#
# Usage:
#   scripts/smoke-test-azure.sh
#   COMPOSE=examples/hello/compose.yml scripts/smoke-test-azure.sh
#   KEEP=1 scripts/smoke-test-azure.sh          # skip teardown to inspect resources
#   STATE_RG=... NAME=ci42 scripts/smoke-test-azure.sh --destroy-only
#
# Requires: terraform, uv (composey), curl, az (Azure CLI)
#
set -euo pipefail

# --- Config (override via environment) --------------------------------------
NAME="${NAME:-smoke}"                                 # environment name
COMPOSE="${COMPOSE:-examples/hello/compose.yml}"      # app to deploy
PROJECT="${PROJECT:-hello}"                            # composey project name
HTTP_PATH="${HTTP_PATH:-/}"                            # path to poll
EXPECT="${EXPECT:-Server name}"                        # string expected in HTTP body
POLL_TIMEOUT="${POLL_TIMEOUT:-300}"                    # seconds to wait for healthy app
KEEP="${KEEP:-0}"                                      # 1 = do not destroy afterwards
STATE_RG="${STATE_RG:-}"                               # Resource Group for remote state; empty = local
STATE_LOCATION="${STATE_LOCATION:-eastus}"             # location of STATE_RG storage
STATE_ACCOUNT="${STATE_ACCOUNT:-composeyacceptstate}"  # storage account holding state
STATE_CONTAINER="${STATE_CONTAINER:-tfstate}"          # blob container within it

# Resolve paths relative to the repo root (this script lives in scripts/).
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_DIR="$ROOT/build/$NAME-environment-azure"          # generated by 'composey init env'
BUILD_DIR="$ROOT/build/$PROJECT-azure"

TF="terraform"

log()  { printf '\n\033[1;34m==>\033[0m %s\n' "$*"; }
fail() { printf '\n\033[1;31mFAIL:\033[0m %s\n' "$*" >&2; exit 1; }

# --- Remote state ------------------------------------------------------------
# State on a CI runner is ephemeral. When STATE_RG is set we use an Azure Blob
# Storage backend so a leaked run stays destroyable from any machine.
#
# The storage account has shared-key access disabled, so the backend must
# authenticate with Entra ID (use_azuread_auth) rather than an account key.
# That works from the CI service principal and from a developer's az login
# alike, provided the identity holds Storage Blob Data Contributor on the
# account. See ci/README.md.
write_backend() {
  local dir="$1" key="$2"
  [[ -n "$STATE_RG" ]] || return 0
  # Falling back to local state here is what previously made a leaked run
  # unrecoverable, so a half-configured backend is an error, not a warning.
  [[ -n "$STATE_ACCOUNT" ]] || fail "STATE_RG is set but STATE_ACCOUNT is empty: refusing to fall back to local state"
  cat > "$dir/backend_ci.tf" <<TF
# Generated by scripts/smoke-test-azure.sh — not checked in.
terraform {
  backend "azurerm" {
    resource_group_name  = "$STATE_RG"
    storage_account_name = "$STATE_ACCOUNT"
    container_name       = "$STATE_CONTAINER"
    key                  = "$key"
    use_azuread_auth     = true
  }
}
TF
}

state_hint() {
  [[ -n "$STATE_RG" ]] || return 0
  echo "  State kept at $STATE_ACCOUNT/$STATE_CONTAINER/acceptance/$NAME/ — destroy later with:"
  echo "    STATE_RG=$STATE_RG NAME=$NAME PROJECT=$PROJECT scripts/smoke-test-azure.sh --destroy-only"
}

# --- Teardown ----------------------------------------------------------------
CLEANED=0
cleanup() {
  local status=$?
  [[ "$CLEANED" == "1" ]] && exit $status
  CLEANED=1

  if [[ "$KEEP" == "1" ]]; then
    log "KEEP=1 set — leaving resources up. Destroy later with:"
    echo "  (cd $BUILD_DIR && $TF destroy -auto-approve)"
    echo "  (cd $ENV_DIR && $TF destroy -auto-approve)"
    exit $status
  fi

  log "Tearing down (exit status $status)…"
  local leaked=0
  
  # Ensure we use Azure CLI auth for teardown
  export ARM_USE_CLI=true
  export ARM_USE_MSI=false
  unset ARM_CLIENT_ID ARM_CLIENT_SECRET ARM_TENANT_ID 2>/dev/null || true
  
  if [[ -d "$BUILD_DIR" ]]; then
    (cd "$BUILD_DIR" && eval "$TF destroy -auto-approve") \
      || { leaked=1; echo "WARNING: app destroy failed — CHECK THE CONSOLE for orphaned resources."; }
  fi
  if [[ -d "$ENV_DIR" ]]; then
    (cd "$ENV_DIR" && eval "$TF destroy -auto-approve") \
      || { leaked=1; echo "WARNING: environment destroy failed — CHECK RESOURCE GROUP manually."; }
  fi

  (( leaked == 1 )) && state_hint
  exit $status
}
trap cleanup EXIT INT TERM

# --- Destroy-only mode -------------------------------------------------------
if [[ "${1:-}" == "--destroy-only" ]]; then
  [[ -n "$STATE_RG" ]] || fail "--destroy-only needs STATE_RG (runs with local state are not recoverable)"
  log "Destroy-only mode for environment '$NAME'."

  write_backend "$ENV_DIR" "acceptance/$NAME/environment.tfstate"
  (cd "$ENV_DIR" && eval "$TF init -input=false -reconfigure")

  if [[ -f "$BUILD_DIR/main.tf.json" ]]; then
    write_backend "$BUILD_DIR" "acceptance/$NAME/$PROJECT.tfstate"
    (cd "$BUILD_DIR" && eval "$TF init -input=false -reconfigure")
  else
    rm -rf "$BUILD_DIR"
    echo "  NOTE: no $BUILD_DIR/main.tf.json — skipping the app stack."
    echo "        To destroy it too, first run:"
    echo "          uv run composey main -f \$COMPOSE -e $ENV_DIR/environment.yml -p $PROJECT -o $BUILD_DIR"
  fi

  exit 0
fi

# --- 1. Create environment with composey init env ----------------------------
log "Creating Azure environment '$NAME' with composey init env…"
rm -rf "$ENV_DIR"
cd "$ROOT"
uv run composey init --provider azure --name "$NAME" --region "$STATE_LOCATION" --output "$ENV_DIR"

write_backend "$ENV_DIR" "acceptance/$NAME/environment.tfstate"
cd "$ENV_DIR"

# Ensure we use Azure CLI auth, not SP env vars
export ARM_USE_CLI=true
export ARM_USE_MSI=false
unset ARM_CLIENT_ID ARM_CLIENT_SECRET ARM_TENANT_ID 2>/dev/null || true

eval "$TF init -input=false -reconfigure"
eval "$TF apply -auto-approve"

# Get the Container Apps Environment info from the output
log "Environment created. Getting Container App info..."

# --- 2. Compile the app ------------------------------------------------------
log "Compiling $COMPOSE with composey for Azure…"
cd "$ROOT"
uv run composey main -f "$COMPOSE" -e "$ENV_DIR/environment.yml" -p "$PROJECT" -o "$BUILD_DIR"

# --- 3. Deploy the app -------------------------------------------------------
log "Deploying app '$PROJECT' to Azure…"
write_backend "$BUILD_DIR" "acceptance/$NAME/$PROJECT.tfstate"
cd "$BUILD_DIR"

# Ensure we use Azure CLI auth, not SP env vars
export ARM_USE_CLI=true
export ARM_USE_MSI=false
unset ARM_CLIENT_ID ARM_CLIENT_SECRET ARM_TENANT_ID 2>/dev/null || true

eval "$TF init -input=false -reconfigure"
eval "$TF apply -auto-approve"

# --- 4. Get Container App FQDN and poll -------------------------------------
# Get the FQDN from the deployed container app
CONTAINER_APP_FQDN="$(eval "$TF output -raw fqdn 2>/dev/null || echo ''")"

# If no explicit output, try to get it from the first container app resource
if [[ -z "$CONTAINER_APP_FQDN" ]]; then
  log "No explicit FQDN output, checking for container_app resource..."
  # Try to extract FQDN from terraform state
  # eval only the terraform invocation; the pipeline stays outside it, which is
  # what the escaping here previously got wrong badly enough to unbalance the
  # script's quoting.
  CONTAINER_APP_FQDN="$(eval "$TF state show 'azurerm_container_app.main'" 2>/dev/null \
    | grep 'fqdn' | head -1 | awk '{print $3}' | tr -d '"' || true)"
fi

[[ -n "$CONTAINER_APP_FQDN" ]] || fail "No Container App FQDN found"
log "Container App FQDN: $CONTAINER_APP_FQDN"

url="https://$CONTAINER_APP_FQDN$HTTP_PATH"
log "Polling $url (up to ${POLL_TIMEOUT}s)…"
deadline=$(( SECONDS + POLL_TIMEOUT ))
served=0
body=""
while (( SECONDS < deadline )); do
  body="$(curl -sS --max-time 5 "$url" 2>/dev/null || true)"
  if [[ "$body" == *"$EXPECT"* ]]; then
    served=1
    break
  fi
  printf '.'
  sleep 5
done
if (( served != 1 )); then
  echo
  echo "----- last response (for diagnosis) -----"
  echo "${body:-<no response>}" | head -20
  fail "timed out after ${POLL_TIMEOUT}s waiting for '$EXPECT' at $url"
fi

log "App is live — response contains '$EXPECT'. 🎉"
echo "----- response -----"
echo "$body" | head -20

# --- 5. Managed-resource assertions ------------------------------------------
log "Asserting managed substitutions against applied Azure state…"
( cd "$BUILD_DIR" && eval "$TF show -json" ) | python3 "$ROOT/scripts/assert_managed.py" \
  || fail "managed substitution assertions failed"

log "SUCCESS — everything verified on real Azure."
exit 0
