#!/usr/bin/env bash
#
# End-to-end smoke test against real AWS.
#
# Deploys the bootstrap environment (VPC + shared ALB + ECS cluster), compiles a
# compose file with composey, deploys the resulting app, then polls the ALB URL
# until it serves a page. EVERYTHING is torn down on exit (success or failure)
# via a trap, so a crashed run does not leave NAT gateways billing.
#
# Usage:
#   scripts/smoke-test.sh
#   PROFILE=personal COMPOSE=examples/hello/compose.yml scripts/smoke-test.sh
#   PROFILE= scripts/smoke-test.sh        # empty PROFILE: use ambient creds (CI)
#   KEEP=1 scripts/smoke-test.sh          # skip teardown to inspect resources
#   STATE_BUCKET=... NAME=ci42 scripts/smoke-test.sh --destroy-only
#                                         # tear down a run that leaked
#
# Requires: terraform, uv (composey), curl. Locally also aws-vault (PROFILE names
# the profile); in CI set PROFILE= (empty) to run terraform with ambient AWS
# credentials (e.g. an OIDC-assumed role).
#
set -euo pipefail

# --- Config (override via environment) --------------------------------------
PROFILE="${PROFILE-personal}"                        # aws-vault profile; empty = ambient creds
NAME="${NAME:-smoke}"                                 # environment name
COMPOSE="${COMPOSE:-examples/hello/compose.yml}"      # app to deploy
PROJECT="${PROJECT:-hello}"                            # composey project name
HTTP_PATH="${HTTP_PATH:-/}"                            # path to poll on the ALB
EXPECT="${EXPECT:-Server name}"                        # string expected in HTTP body
POLL_TIMEOUT="${POLL_TIMEOUT:-300}"                    # seconds to wait for healthy ALB
                                                       # (ALB default health check needs
                                                       # 5×30s + Fargate cold start)
KEEP="${KEEP:-0}"                                      # 1 = do not destroy afterwards
STATE_BUCKET="${STATE_BUCKET:-}"                       # S3 bucket for remote state; empty = local
STATE_REGION="${STATE_REGION:-eu-west-2}"              # region of STATE_BUCKET

# Resolve paths relative to the repo root (this script lives in scripts/).
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BOOTSTRAP_DIR="$ROOT/bootstrap"
BUILD_DIR="$ROOT/build/$PROJECT"

# With a profile, wrap terraform in aws-vault (local); without one, run it
# directly against the ambient AWS credentials (CI / OIDC-assumed role).
if [[ -n "$PROFILE" ]]; then
  TF="aws-vault exec $PROFILE -- terraform"
else
  TF="terraform"
fi

log()  { printf '\n\033[1;34m==>\033[0m %s\n' "$*"; }
fail() { printf '\n\033[1;31mFAIL:\033[0m %s\n' "$*" >&2; exit 1; }

# --- Remote state ------------------------------------------------------------
# State on a CI runner is ephemeral: if the run is cancelled or the runner dies,
# a local state file dies with it and everything it created (NAT gateway, ALB,
# RDS…) bills forever with no way to `terraform destroy` it. When STATE_BUCKET is
# set we drop an S3 backend into each state directory, keyed by run NAME, so a
# leaked run stays destroyable from any machine. Without it we fall back to local
# state, which is fine on a laptop where the files persist.
write_backend() {
  local dir="$1" key="$2"
  [[ -n "$STATE_BUCKET" ]] || return 0
  cat > "$dir/backend_ci.tf" <<TF
# Generated by scripts/smoke-test.sh — not checked in.
terraform {
  backend "s3" {
    bucket  = "$STATE_BUCKET"
    key     = "$key"
    region  = "$STATE_REGION"
    encrypt = true
  }
}
TF
}

state_hint() {
  [[ -n "$STATE_BUCKET" ]] || return 0
  echo "  State kept at s3://$STATE_BUCKET/acceptance/$NAME/ — destroy later with:"
  echo "    STATE_BUCKET=$STATE_BUCKET NAME=$NAME PROJECT=$PROJECT scripts/smoke-test.sh --destroy-only"
}

# --- Teardown ----------------------------------------------------------------
# Runs on ANY exit, including cancellation. Destroy app first (it depends on
# bootstrap), then bootstrap.
CLEANED=0
cleanup() {
  local status=$?
  # INT/TERM run this and then fall through to the EXIT trap; only act once.
  [[ "$CLEANED" == "1" ]] && exit $status
  CLEANED=1

  if [[ "$KEEP" == "1" ]]; then
    log "KEEP=1 set — leaving resources up. Destroy later with:"
    echo "  (cd $BUILD_DIR && $TF destroy -auto-approve)"
    echo "  (cd $BOOTSTRAP_DIR && $TF destroy -auto-approve -var name=$NAME)"
    exit $status
  fi

  log "Tearing down (exit status $status)…"
  local leaked=0
  if [[ -d "$BUILD_DIR" ]]; then
    (cd "$BUILD_DIR" && eval "$TF destroy -auto-approve") \
      || { leaked=1; echo "WARNING: app destroy failed — CHECK THE CONSOLE for orphaned resources."; }
  fi
  (cd "$BOOTSTRAP_DIR" && eval "$TF destroy -auto-approve -var name=$NAME") \
    || { leaked=1; echo "WARNING: bootstrap destroy failed — CHECK NAT GATEWAYS / EIPs / ALB manually."; }

  (( leaked == 1 )) && state_hint
  exit $status
}
trap cleanup EXIT INT TERM

# --- Destroy-only mode -------------------------------------------------------
# Recovery path for a run that leaked: re-point at its remote state and tear it
# down. Requires STATE_BUCKET and the NAME the leaked run used.
if [[ "${1:-}" == "--destroy-only" ]]; then
  [[ -n "$STATE_BUCKET" ]] || fail "--destroy-only needs STATE_BUCKET (runs with local state are not recoverable)"
  log "Destroy-only mode for environment '$NAME'."

  write_backend "$BOOTSTRAP_DIR" "acceptance/$NAME/bootstrap.tfstate"
  (cd "$BOOTSTRAP_DIR" && eval "$TF init -input=false -reconfigure")

  # Destroying the app stack needs its generated config, not just its state:
  # Terraform cannot configure the AWS provider from an empty directory. If the
  # manifest is missing, recompile it with the same compose file and project
  # name first; the bootstrap teardown below still runs either way.
  if [[ -f "$BUILD_DIR/main.tf.json" ]]; then
    write_backend "$BUILD_DIR" "acceptance/$NAME/$PROJECT.tfstate"
    (cd "$BUILD_DIR" && eval "$TF init -input=false -reconfigure")
  else
    rm -rf "$BUILD_DIR"   # nothing to destroy from; skip it in cleanup
    echo "  NOTE: no $BUILD_DIR/main.tf.json — skipping the app stack."
    echo "        To destroy it too, first run:"
    echo "          uv run composey -f \$COMPOSE -e $BOOTSTRAP_DIR/environment.yml -p $PROJECT -o $BUILD_DIR"
  fi

  exit 0   # the EXIT trap does the actual destroying
fi

# --- 1. Deploy bootstrap -----------------------------------------------------
log "Deploying bootstrap environment '$NAME'…"
write_backend "$BOOTSTRAP_DIR" "acceptance/$NAME/bootstrap.tfstate"
cd "$BOOTSTRAP_DIR"
eval "$TF init -input=false -reconfigure"
eval "$TF apply -auto-approve -var name=$NAME"

ALB_DNS="$(eval "$TF output -raw alb_dns_name")"
[[ -n "$ALB_DNS" ]] || fail "bootstrap produced no alb_dns_name"
log "Environment up. ALB: $ALB_DNS"

# --- 2. Compile the app ------------------------------------------------------
log "Compiling $COMPOSE with composey…"
cd "$ROOT"
uv run composey -f "$COMPOSE" -e "$BOOTSTRAP_DIR/environment.yml" -p "$PROJECT" -o "$BUILD_DIR"

# --- 3. Deploy the app -------------------------------------------------------
log "Deploying app '$PROJECT'…"
write_backend "$BUILD_DIR" "acceptance/$NAME/$PROJECT.tfstate"
cd "$BUILD_DIR"
eval "$TF init -input=false -reconfigure"
eval "$TF apply -auto-approve"

# --- 4. Poll the ALB until it serves the app ---------------------------------
url="http://$ALB_DNS$HTTP_PATH"
log "Polling $url (up to ${POLL_TIMEOUT}s)…"
deadline=$(( SECONDS + POLL_TIMEOUT ))
served=0
body=""
while (( SECONDS < deadline )); do
  # No -f: capture non-2xx bodies (e.g. a 503 /health) for the EXPECT match and
  # for diagnostics on timeout.
  body="$(curl -sS --max-time 5 "$url" 2>/dev/null || true)"
  if [[ "$body" == *"$EXPECT"* ]]; then
    served=1
    break
  fi
  printf '.'
  sleep 5
done
if (( served != 1 )); then
  echo
  echo "----- last response (for diagnosis) -----"
  echo "${body:-<no response>}" | head -20
  fail "timed out after ${POLL_TIMEOUT}s waiting for '$EXPECT' at $url"
fi

log "App is live — response contains '$EXPECT'. 🎉"
echo "----- response -----"
echo "$body" | head -20

# --- 5. Managed-resource assertions ------------------------------------------
# Prove every substituted service (minio->S3, postgres->RDS, redis->ElastiCache)
# really landed in AWS and that endpoint injection reached the deployed task.
# Driven off applied TF state; a no-op for examples with nothing substituted.
log "Asserting managed substitutions against applied AWS state…"
( cd "$BUILD_DIR" && eval "$TF show -json" ) | python3 "$ROOT/scripts/assert_managed.py" \
  || fail "managed substitution assertions failed"

log "SUCCESS — everything verified on real AWS."
exit 0
